#!/bin/sh /etc/rc.common
 
START=11
 
# don't run within buildroot
[ -n "${IPKG_INSTROOT}" ] && return 0
 
# use busybox grep as GNU grep may behave differently
grep(){
    /bin/busybox 'grep' $@
}
 
# shutdown interfaces and assign temporary names
for i in $( ls /sys/class/net/*/device/uevent | awk -F'/' '{print $5}' | tr '\n' ' ' ) ;
do
 
    mac_address=$( grep $i /etc/config/mac-static-interfaces | awk '{print $3}' | tr -d '"' )
 
    if [ "$mac_address" != '' ]; then
 
        ip link set "$i" down
        ip link set "$i" name old"$i"
 
    fi
done
 
# assign configured interface names based on MAC address
for i in $( ls /sys/class/net/*/device/uevent | awk -F'/' '{print $5}' | tr '\n' ' ' ) ;
do
 
    mac_address=$( cat /sys/class/net/$i/address )
    interface_name=$( grep -i $mac_address /etc/config/mac-static-interfaces | awk '{print $2}' )
 
    if [ "$interface_name" != '' ]; then
 
        ip link set "$i" down
        ip link set "$i" name "$interface_name"
 
    fi
done
